### ISSUE TITLE
pip install failure on debian:8 `UnicodeDecodeError: 'ascii' codec can't decode byte 0xef`

### ISSUE THREAD

**Issue by jamshid** [tpltnt/pyutil#2]
I think there is a Unicode BOM at beginning of README.rst, and that causes install problems, at least in my debian jessie Dockerfile with python 2.7.9.

Workaround:
```
 pip --verbose install 'pyutil<3'
```

```
root@08846e692ec2:/# pip --verbose install pyutil
Downloading/unpacking pyutil
  Using version 3.0.0 (newest of versions: 3.0.0, 2.1.0, 2.0.1, 2.0.0, 1.9.7, 1.9.6, 1.9.4, 1.9.3, 1.9.2, 1.9.1, 1.9.0, 1.8.8, 1.8.7, 1.8.6, 1.8.4, 1.8.3, 1.8.2, 1.8.1, 1.8.0, 1.7.12, 1.7.11, 1.7.10, 1.7.9, 1.7.8, 1.7.7, 1.7.6, 1.7.5, 1.7.4, 1.7.3, 1.7.2, 1.7.1)
  Downloading pyutil-3.0.0.tar.gz (236kB): 
  Downloading from URL https://pypi.python.org/packages/e4/e6/5c9a5cd2127473e47f9a27cd0aba97d7897d022e6f641317b69a28b2f7e0/pyutil-3.0.0.tar.gz#md5=4bea733686270a5a8b51ca7aa4350612 (from https://pypi.python.org/simple/pyutil/)
...Downloading pyutil-3.0.0.tar.gz (236kB): 236kB downloaded
  Running setup.py (path:/tmp/pip-build-G8tdjH/pyutil/setup.py) egg_info for package pyutil
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-G8tdjH/pyutil/setup.py", line 49, in <module>
        readmetext = io.open(u'README.rst').read()
      File "/usr/lib/python2.7/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 0: ordinal not in range(128)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-G8tdjH/pyutil/setup.py", line 49, in <module>

    readmetext = io.open(u'README.rst').read()

  File "/usr/lib/python2.7/encodings/ascii.py", line 26, in decode

    return codecs.ascii_decode(input, self.errors)[0]

UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 0: ordinal not in range(128)

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-G8tdjH/pyutil
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1230, in prepare_files
    req_to_install.run_egg_info()
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 326, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 716, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-G8tdjH/pyutil

Storing debug log for failure in /root/.pip/pip.log
root@08846e692ec2:/# 
```

**Comment by tpltnt** [comment]
Good catch, I will look into it.

**Comment by tpltnt** [comment]
Can't be reproduced on Debian 9.1 ("stretch") with Python 2.7.13.

**Comment by tpltnt** [comment]
@jamshid can you check the `issue-2` branch by installing manually via `python setup.py install` ?

**Comment by jamshid** [comment]
How do I get the issue-2 branch? I did `git clone https://github.com/tpltnt/pyutil.git` then `git checkout -b issue-2` but git says it's a "new branch".

You can reproduce the failure easily with docker:
```
$ docker run -ti debian:jessie
# apt update
# apt install python-pip
# pip install pyutil
Downloading/unpacking pyutil
  Downloading pyutil-3.0.0.tar.gz (236kB): 236kB downloaded
  Running setup.py (path:/tmp/pip-build-P9Rx36/pyutil/setup.py) egg_info for package pyutil
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-P9Rx36/pyutil/setup.py", line 49, in <module>
        readmetext = io.open(u'README.rst').read()
      File "/usr/lib/python2.7/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 0: ordinal not in range(128)
```

**Comment by jamshid** [comment]
I needed `git checkout issue-2`, without `-b`. 
Yup that fixed it feel free to close.

**Comment by tpltnt** [comment]
@jamshid thank you for spotting the bug and your feedback. I pushed version 3.1.0 to pypi.
