### ISSUE TITLE
Cannot install or use on PyPy

### ISSUE THREAD

**Issue by exarkun** [tpltnt/pyutil#4]
```
Collecting pyutil>=3.0.0 (from zfec>=1.1.0->tahoe-lafs==0.0.0)
  Downloading https://files.pythonhosted.org/packages/a3/6a/dac88efc61636269c97e0fef12fe797c1ff27e9c24539727db717fffcb34/pyutil-3.2.0.tar.gz (292kB)
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<module>", line 1, in <module>
      File "/tmp/pip-wheel-u9mVmm/pyutil/setup.py", line 0
    SyntaxError: UTF-8 BOM with utf-8-with-signature-unix coding cookie
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-wheel-u9mVmm/pyutil/
```

The source files appear to declare one kind of encoding but use another.  This seems to pass silently on CPython but it blows up on PyPy.

Both the declaration and the BOM seem like relics that could just be dropped.

**Comment by exarkun** [comment]
According to this ancient PEP, https://www.python.org/dev/peps/pep-0263/, using UTF-8 BOM w/ a coding cookie other than "utf-8" is illegal.  Though it seems CPython doesn't correctly implement this behavior.
